name: Build Linux Packages

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  APP_NAME: "My App"
  APP_BINARY_NAME: "MyApp"
  APP_VERSION: "1.0.0"
  PUBLISHER: "Publisher Name"
  BUILD_AUTOMATION_PATH: "build automation"
  LINUX_BUILD_SCRIPT: "build-linux.sh"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g @neutralinojs/neu
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          fuse \
          libfuse2 \
          rpm \
          alien \
          desktop-file-utils \
          wget \
          curl \
          jq

    - name: Install AppImage tools
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
        
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        sudo mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy

    - name: Build Neutralino app
      run: |
        neu build

    - name: Build Linux packages
      run: |
        chmod +x "${{ env.BUILD_AUTOMATION_PATH }}/${{ env.LINUX_BUILD_SCRIPT }}"
        "./${{ env.BUILD_AUTOMATION_PATH }}/${{ env.LINUX_BUILD_SCRIPT }}" --appimage --deb --rpm
      
    - name: Upload Linux builds
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          dist/linux_*/*.AppImage
          dist/linux_*/*.deb
          dist/linux_*/*.rpm
        retention-days: 90

    - name: Create Release (on tags)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/linux_*/*.AppImage
          dist/linux_*/*.deb
          dist/linux_*/*.rpm
        name: ${{ env.APP_NAME }} ${{ env.APP_VERSION }}
        body: |
          ## ${{ env.APP_NAME }} v${{ env.APP_VERSION }}
          
          ### Linux Downloads
          - **AppImage (Universal)**: ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.AppImage
          - **Debian/Ubuntu**: ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-amd64.deb
          - **RedHat/Fedora**: ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.rpm
          
          ### Installation Instructions
          
          #### AppImage (Recommended - works on all distributions)
          ```bash
          # Download the AppImage
          chmod +x ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.AppImage
          ./${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.AppImage
          ```
          
          #### Debian/Ubuntu
          ```bash
          sudo dpkg -i ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-amd64.deb
          sudo apt-get install -f  # Fix any dependency issues
          ```
          
          #### RedHat/Fedora/CentOS
          ```bash
          sudo rpm -i ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.rpm
          # or
          sudo dnf install ${{ env.APP_BINARY_NAME }}-${{ env.APP_VERSION }}-x86_64.rpm
          ```
          
          **Note**: All packages are unsigned but fully functional.
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 